### ISSUE TITLE
Doesn't discover v10 based DataPower images

### ISSUE THREAD

**Issue by rickymoorhouse** [IBM/apiconnect-trawler#3]
The annotations of a v10 datapower look like this:
```
  annotations:
    datapower.ibm.com/domains.apiconnect.reconciled: "2020-09-28T14:29:43Z"
    datapower.ibm.com/domains.default.reconciled: "2020-09-28T14:29:43Z"
    datapower.ibm.com/user.admin.reconciled: "2020-09-28T14:29:43Z"
    datapower.ibm.com/username.commands.reconciled: "2020-09-28T14:29:43Z"
    kubernetes.io/psp: ibm-privileged-psp
    productChargedContainers: datapower
    productID: 887a7b80dd7b40c9b978ff085230604e
    productMetric: VIRTUAL_PROCESSOR_CORE
    productName: IBM DataPower Gateway Virtual Edition - Production Edition
    productVersion: 10.0.0.0
    prometheus.io/module: dpStatusMIB
    prometheus.io/path: /snmp
    prometheus.io/port: "63512"
    prometheus.io/scrape: "true"
    prometheus.io/target: 127.0.0.1:1161
```

Where as a v2018 datapower looks like:
```
  annotations:
    kubernetes.io/psp: ibm-privileged-psp
    productChargedContainers: ""
    productFlexpointBundle: ""
    productID: IBMDataPowerGatewayVirtualEdition_2018.4.1.13...
    productName: IBM DataPower Gateway Virtual Edition for Developers
    productVersion: 2018.4.1.13-324822-release-prod
    prometheus.io/module: dpStatusMIB
    prometheus.io/path: /snmp?target=127.0.0.1:1161&module=dpStatusMIB
    prometheus.io/port: "63512"
    prometheus.io/scrape: "true"
    prometheus.io/target: 127.0.0.1:1161
    restPort: "5554"
    sshPort: "9022"
    webGUIPort: "9090"
```

Currently trawler is looking for restPort - so doesn't find the v10 pods.  

Looking to move to using the productName annotation instead for discovery
